
- name: Check that template.j2 exists
  stat:
    path: template.j2
  register: stat_result

- name: alert if it doesnt
  debug: msg="template doesn't exist"
  when: stat_result.stat.exists == False 

- name: template exists
  debug: msg="PASS"
  when: stat_result.stat.exists == True

- name: set fact
  set_fact:
    template_exists: yes
  when: stat_result.stat.exists == True

