    - name: compare old and new files
      shell: diff "{{ playbook_dir }}/{{inventory_hostname}}_old.txt" "{{ playbook_dir }}/{{inventory_hostname }}_new.txt"
      failed_when: "tulos.rc > 1"
      register: tulos



    - name: write comapring results on separate files
      copy:
        dest: "{{ playbook_dir }}/{{ inventory_hostname }}_comparing_results.txt"
        content: "{{tulos}}"
      tags: 'compare'



    - name: print diff
      debug: msg="{{tulos['stdout_lines']}}"

