- name: Get device facts and configuration
  hosts: vqfx10k
  roles:
    - Juniper.junos
  connection: local
  gather_facts: no

  tasks:
    - name: Retrieve device facts and configuration and save facts to file
      juniper_junos_facts:        
        savedir: "{{ playbook_dir }}"
        config_format: "xml"
        host: "{{ ansible_ssh_host }}"
        port: "{{ ansible_ssh_port }}"
        user: root
        passwd: Juniper
      register: result

    - name: Print configuration
      debug:
        var: result.ansible_facts.junos.config
