# This task gets all Junos configuration from all devices
- name: Generate and Deploy Configuration
  hosts: vqfx10k
  connection: local
  gather_facts: no
  
  tasks:
    - name: Build configuration
      include: createconfigs.yml
    - name: Deploy config to device
      junos_config:
        update: override
        src: "conf/{{ inventory_hostname }}.conf"
        
 
    - name: gather facts
      junos_facts: 
        config_format: text
        gather_subset: config
      register: result

    - name: remove compare folder
      file:
        state: absent
        path: compare/
      run_once: yes


    - name: write results on separate files
      lineinfile:
        path: "{{ playbook_dir }}/compare/{{ inventory_hostname }}.txt"
        state: present
        line: "{{result.ansible_facts.ansible_net_config}}"
        create: yes

    - name: check bgp neighbors
      junos_command: 
        commands: show bgp summary | display json
      register: bgp
      tags: 'testi'
#    - name: debug that
#      debug: msg="{{bgp.stdout}}"

    - name: write results on separate files
      lineinfile:
        path: "{{ playbook_dir }}/{{ inventory_hostname }}_bgp.txt"
        state: present
        line: "{{bgp['stdout_lines']}}"
        create: yes
      tags: 'testi'
    - name: read conf files for comparing
      debug: msg="{{lookup('file','conf/{{inventory_hostname}}.conf')}}"
      register: original

    - name: write original files to same format
      lineinfile:
        path: "{{ playbook_dir }}/compare/{{ inventory_hostname }}_original.txt"
        state: present
        line: "{{original.msg}}"
        create: yes
      
