
- name: Generate and Deploy Configuration
  hosts: vqfx10k
  connection: local
  gather_facts: no
  roles:
    - Juniper.junos
  tasks:
    - name: include needed files
      include_vars:
        dir: host_vars
        extensions:
          - yml
          - yaml
      
    - name: Build configuration
      template: src=template.j2 dest=conf/{{ inventory_hostname }}.conf
