
- name: include needed files
  include_vars:
    dir: host_vars
    extensions:
      - yml
      - yaml
      
- name: Build configuration
  template: src=template.j2 dest=conf/{{ inventory_hostname }}.conf
